### ISSUE TITLE
roadmap for version 1.1 (cesium)

### ISSUE THREAD

**Issue by foobarbecue** [foobarbecue/climbshare#34]
- [ ] Get cliffs to display
- [ ] Get climbs to display
- [ ] Improve cliff loading efficiency (tiles or similar)

**Comment by foobarbecue** [comment]
Cancelled in favor of Nexus
